<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomFurnitureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('room_furniture')->insert([
            // ============================================
            // COMPUTER LAB ROOMS (Small: L-001 to L-003, capacity 25)
            // ============================================
            
            // SDS L-001 (Computer Lab - Small, capacity 25)
            [
                'room_id' => 1,
                'furniture_name' => 'Computer',
                'quantity' => 25,
                'description' => 'Desktop computers for students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Chairs',
                'quantity' => 25,
                'description' => 'Office chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Tables',
                'quantity' => 6,
                'description' => 'Long tables (seats 4 students each) for computers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Portable whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 12,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Extension Wires',
                'quantity' => 8,
                'description' => 'Heavy-duty power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 1,
                'furniture_name' => 'Storage Cabinet',
                'quantity' => 2,
                'description' => 'For storing lab materials and equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-002 (Computer Lab - Small, capacity 25)
            [
                'room_id' => 2,
                'furniture_name' => 'Computer',
                'quantity' => 25,
                'description' => 'Desktop computers for students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Chairs',
                'quantity' => 25,
                'description' => 'Office chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Tables',
                'quantity' => 6,
                'description' => 'Long tables (seats 4 students each) for computers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Portable whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 12,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Extension Wires',
                'quantity' => 8,
                'description' => 'Heavy-duty power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'furniture_name' => 'Storage Cabinet',
                'quantity' => 2,
                'description' => 'For storing lab materials and equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-003 (Computer Lab - Small, capacity 25)
            [
                'room_id' => 3,
                'furniture_name' => 'Computer',
                'quantity' => 25,
                'description' => 'Desktop computers for students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Chairs',
                'quantity' => 25,
                'description' => 'Office chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Tables',
                'quantity' => 6,
                'description' => 'Long tables (seats 4 students each) for computers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Portable whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 12,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Extension Wires',
                'quantity' => 8,
                'description' => 'Heavy-duty power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'furniture_name' => 'Storage Cabinet',
                'quantity' => 2,
                'description' => 'For storing lab materials and equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ============================================
            // COMPUTER LAB ROOMS (Large: L-004 to L-005, capacity 50)
            // ============================================

            // SDS L-004 (Computer Lab - Large, capacity 50)
            [
                'room_id' => 4,
                'furniture_name' => 'Computer',
                'quantity' => 50,
                'description' => 'Desktop computers for students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Chairs',
                'quantity' => 50,
                'description' => 'Office chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Tables',
                'quantity' => 13,
                'description' => 'Long tables (seats 4 students each) for computers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Whiteboard',
                'quantity' => 2,
                'description' => 'Portable whiteboards',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 20,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Extension Wires',
                'quantity' => 12,
                'description' => 'Heavy-duty power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 4,
                'furniture_name' => 'Storage Cabinet',
                'quantity' => 3,
                'description' => 'For storing lab materials and equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-005 (Computer Lab - Large, capacity 50)
            [
                'room_id' => 5,
                'furniture_name' => 'Computer',
                'quantity' => 50,
                'description' => 'Desktop computers for students',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Chairs',
                'quantity' => 50,
                'description' => 'Office chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Tables',
                'quantity' => 13,
                'description' => 'Long tables (seats 4 students each) for computers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Whiteboard',
                'quantity' => 2,
                'description' => 'Portable whiteboards',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 20,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Extension Wires',
                'quantity' => 12,
                'description' => 'Heavy-duty power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'furniture_name' => 'Storage Cabinet',
                'quantity' => 3,
                'description' => 'For storing lab materials and equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ============================================
            // LECTURE ROOMS (Small: L-101 to L-104, capacity 15)
            // ============================================

            // SDS L-101 (Lecture Room - Small, capacity 15)
            [
                'room_id' => 6,
                'furniture_name' => 'Chairs',
                'quantity' => 15,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Tables',
                'quantity' => 2,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 6,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Extension Wires',
                'quantity' => 4,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'furniture_name' => 'Marker Set',
                'quantity' => 1,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-102 (Lecture Room - Small, capacity 15)
            [
                'room_id' => 7,
                'furniture_name' => 'Chairs',
                'quantity' => 15,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Tables',
                'quantity' => 2,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 6,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Extension Wires',
                'quantity' => 4,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 7,
                'furniture_name' => 'Marker Set',
                'quantity' => 1,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-103 (Lecture Room - Small, capacity 15)
            [
                'room_id' => 8,
                'furniture_name' => 'Chairs',
                'quantity' => 15,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Tables',
                'quantity' => 2,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 6,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Extension Wires',
                'quantity' => 4,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'furniture_name' => 'Marker Set',
                'quantity' => 1,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-104 (Lecture Room - Small, capacity 15)
            [
                'room_id' => 9,
                'furniture_name' => 'Chairs',
                'quantity' => 15,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Tables',
                'quantity' => 2,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 6,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Extension Wires',
                'quantity' => 4,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'furniture_name' => 'Marker Set',
                'quantity' => 1,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ============================================
            // LECTURE ROOMS (Large: L-105 to L-106, capacity 30)
            // ============================================

            // SDS L-105 (Lecture Room - Large, capacity 30)
            [
                'room_id' => 10,
                'furniture_name' => 'Chairs',
                'quantity' => 30,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Tables',
                'quantity' => 4,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Large wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 10,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Extension Wires',
                'quantity' => 6,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 10,
                'furniture_name' => 'Marker Set',
                'quantity' => 2,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SDS L-106 (Lecture Room - Large, capacity 30)
            [
                'room_id' => 11,
                'furniture_name' => 'Chairs',
                'quantity' => 30,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Tables',
                'quantity' => 4,
                'description' => 'Long tables (seats 7-8 students each) for group work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Large wall-mounted whiteboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector with wireless capability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 10,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Extension Wires',
                'quantity' => 6,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'furniture_name' => 'Marker Set',
                'quantity' => 2,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ============================================
            // TUTORIAL ROOM (T-001, capacity 15)
            // ============================================

            // SDS T-001 (Tutorial Room, capacity 15)
            [
                'room_id' => 12,
                'furniture_name' => 'Chairs',
                'quantity' => 15,
                'description' => 'Student chairs (matching capacity)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Tables',
                'quantity' => 3,
                'description' => 'Long tables (seats 5 students each) for collaborative learning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Whiteboard',
                'quantity' => 1,
                'description' => 'Portable whiteboard on stand',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Projector',
                'quantity' => 1,
                'description' => 'HD Projector for presentations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Wall Sockets',
                'quantity' => 6,
                'description' => 'Electrical wall sockets for devices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Extension Wires',
                'quantity' => 4,
                'description' => 'Power extension cords',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Marker Set',
                'quantity' => 1,
                'description' => 'Whiteboard markers (assorted colors)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'furniture_name' => 'Flip Chart',
                'quantity' => 1,
                'description' => 'Flip chart stand for group discussions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
